name: paae
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pillow
  - tqdm
  - tensorboard
  - pip
  - pip:
      - timm>=0.9.0
      - yacs>=0.1.8
      - einops>=0.6.0
      - opencv-python>=4.7.0
      - opencv-contrib-python>=4.7.0
      - gpustat>=1.1.1
      - pytorch-grad-cam>=1.4.0
      - seaborn>=0.12.0
      - fvcore>=0.1.5.post20221221
      - thop>=0.1.1.post2209072238
